//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Models.Article {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Article {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Article() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Models.Article.Article", typeof(Article).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类.
        /// </summary>
        public static string CateId {
            get {
                return ResourceManager.GetString("CateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email至多不超过30个字符.
        /// </summary>
        public static string Email_Length_Msg {
            get {
                return ResourceManager.GetString("Email_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字段.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 别名.
        /// </summary>
        public static string FieldRename {
            get {
                return ResourceManager.GetString("FieldRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否推荐.
        /// </summary>
        public static string IsCommend {
            get {
                return ResourceManager.GetString("IsCommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否置顶.
        /// </summary>
        public static string IsTop {
            get {
                return ResourceManager.GetString("IsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回复内容.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面重命名.
        /// </summary>
        public static string ReName {
            get {
                return ResourceManager.GetString("ReName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面重命名至多不超过60个字符.
        /// </summary>
        public static string ReName_Length_Msg {
            get {
                return ResourceManager.GetString("ReName_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否允许评论.
        /// </summary>
        public static string ReplyPermit {
            get {
                return ResourceManager.GetString("ReplyPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面描述.
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面描述至多不超过1000个字符.
        /// </summary>
        public static string SeoDescription_Length_Msg {
            get {
                return ResourceManager.GetString("SeoDescription_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面关键字.
        /// </summary>
        public static string Seokeywords {
            get {
                return ResourceManager.GetString("Seokeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面关键字至多不超过500个字符.
        /// </summary>
        public static string Seokeywords_Length_Msg {
            get {
                return ResourceManager.GetString("Seokeywords_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面Metas.
        /// </summary>
        public static string SeoMetas {
            get {
                return ResourceManager.GetString("SeoMetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面Metas至多不超过1000个字符.
        /// </summary>
        public static string SeoMetas_Length_Msg {
            get {
                return ResourceManager.GetString("SeoMetas_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面Title.
        /// </summary>
        public static string SeoTitle {
            get {
                return ResourceManager.GetString("SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面Title至多不超过500个字符.
        /// </summary>
        public static string SeoTitle_Length_Msg {
            get {
                return ResourceManager.GetString("SeoTitle_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 摘要.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 摘要至多不超过400个字符.
        /// </summary>
        public static string Summary_Length_Msg {
            get {
                return ResourceManager.GetString("Summary_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签至多不超过50个字符.
        /// </summary>
        public static string Tags_Length_Msg {
            get {
                return ResourceManager.GetString("Tags_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题至多不超过100个字符.
        /// </summary>
        public static string Title_Length_Msg {
            get {
                return ResourceManager.GetString("Title_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url至多不超过100个字符.
        /// </summary>
        public static string Url_Length_Msg {
            get {
                return ResourceManager.GetString("Url_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名至多不超过20个字符.
        /// </summary>
        public static string UserName_Length_Msg {
            get {
                return ResourceManager.GetString("UserName_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码.
        /// </summary>
        public static string ValidationCode {
            get {
                return ResourceManager.GetString("ValidationCode", resourceCulture);
            }
        }
    }
}
